spring:
  datasource:
    url: jdbc:oracle:thin:@msip-dev.cqklrtezyqhs.ap-northeast-2.rds.amazonaws.com:1521:ORCL
    driver-class-name: oracle.jdbc.OracleDriver
    username: msip
    password: Msip2022!!
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.apache.poi.util.XMLHelper: off