spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:MSPP
    driver-class-name: oracle.jdbc.OracleDriver
    username: EXCEL_TEST
    password: excel_test
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.apache.poi.util.XMLHelper: off